[package]
name = "quad-svg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { path = "../macroquad" }
resvg = "0.28.0"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }